### PR TITLE
Convert core to a full cross project

### PR DESCRIPTION
**Pull request by cquiroz**

### CODE REVIEW

**Comment by tpolecat** [comment]
What's the effect of this change?

**Comment by cquiroz** [comment]
Nothing at the moment, but you can add jvm only tests to core creating a dir core/jvm/src/test/scala

This could be used by @swalker to track the troubles he's having with test resources

**Comment by swalker2m** [comment]
This is what I expected to see originally -- I wasn't familiar with the `Pure` vs. `Full` option.  It seems fine to me. 👍 @tpolecat any reservations?

**Comment by tpolecat** [comment]
Nope, looks fine.

**Pull request merged**
