### PR TITLE
WIP - upgrade to sbt 1.0

### PR DESCRIPTION
**Pull request by tpolecat**
I don't think our build will need any changes other than updating the plugins.

 - [x] flyway-sbt https://github.com/flyway/flyway/issues/1741
 - [x] scalastyle-sbt-plugin 
 - [x] sbt-native-packager   
 - [x] sbt-git               
 - [x] sbt-header            
 - [x] sbt-wartremover       
 - [x] sbt-scalajs           
 - [x] sbt-dependency-graph  https://github.com/jrudolph/sbt-dependency-graph/issues/134
 - [x] sbt-updates

### CODE REVIEW

**Comment by cquiroz** [comment]
Congratulations on getting to sbt 1.0. I don't even want to think about doing that for
Ocs3

**Comment by tpolecat** [comment]
I'm not convinced we want to move. I'm messing around with it in doobie and it's behaving strangely.

**Comment by cquiroz** [comment]
Sbt and strange behavior is the regular state 😄. I guess for doobie you don't need to cross-sbt build but maybe for tut?

**Comment by tpolecat** [comment]
We had to fork tut. There was no way to make it compile for 0.13 and 1.0

**Comment by tpolecat** [comment]
sbt 1.0.3 fixes the issues I ran into, and all the plugins are now available so I think we can merge this if it goes green.

**Comment by tpolecat** [comment]
Hm wonder why scalastyle just now saw that stuff.

**Pull request merged**
