### PR TITLE
syntax for literal things

### PR DESCRIPTION
**Pull request by tpolecat**
This was an experiment but it seems useful for constructing data for testing, and for messing around in the REPL.

### CODE REVIEW

**Comment by swalker2m** [comment]
I like this. 👍 You'll need to rebase and move this file because of the scala-js project format update.

**Comment by tpolecat** [comment]
Oh I thought I rebased already. Standby.

**Comment by cquiroz** [comment]
neat 👍

**Comment by swalker2m** [comment]
Wait, shouldn't this be in `shared/src`?

**Comment by tpolecat** [comment]
Gah, yeah

**Comment by tpolecat** [comment]
Hm it doesn't quite work in JS.

**Comment by tpolecat** [comment]
Ok well it doesn't compile for JS for some reason. I left a message on the gitter channel but I'll close this for now.

**Pull request closed without merging**
